// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: helloworld/helloworld.proto

package helloworld

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	messages "github.com/iissy/go-micro/messages"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Greeter service

type GreeterService interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *messages.HelloRequest, opts ...client.CallOption) (*messages.HelloReply, error)
}

type greeterService struct {
	c    client.Client
	name string
}

func NewGreeterService(name string, c client.Client) GreeterService {
	return &greeterService{
		c:    c,
		name: name,
	}
}

func (c *greeterService) SayHello(ctx context.Context, in *messages.HelloRequest, opts ...client.CallOption) (*messages.HelloReply, error) {
	req := c.c.NewRequest(c.name, "Greeter.SayHello", in)
	out := new(messages.HelloReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterHandler interface {
	// Sends a greeting
	SayHello(context.Context, *messages.HelloRequest, *messages.HelloReply) error
}

func RegisterGreeterHandler(s server.Server, hdlr GreeterHandler, opts ...server.HandlerOption) error {
	type greeter interface {
		SayHello(ctx context.Context, in *messages.HelloRequest, out *messages.HelloReply) error
	}
	type Greeter struct {
		greeter
	}
	h := &greeterHandler{hdlr}
	return s.Handle(s.NewHandler(&Greeter{h}, opts...))
}

type greeterHandler struct {
	GreeterHandler
}

func (h *greeterHandler) SayHello(ctx context.Context, in *messages.HelloRequest, out *messages.HelloReply) error {
	return h.GreeterHandler.SayHello(ctx, in, out)
}
